# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AusCities', '0002_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AusCities.UserType'),
        ),
    ]
