# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AusCities', '0005_auto_20170920_1234'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
