# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AusCities', '0006_auto_20170920_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
